package com.mediLinkAI.services.User;

import jakarta.mail.internet.MimeMessage;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import com.mediLinkAI.dto.Authentication.LoginDTO;
import com.mediLinkAI.dto.Master.ResponseDTO;
import com.mediLinkAI.dto.User.UserDTO;
import com.mediLinkAI.entity.User.OTP;
import com.mediLinkAI.entity.User.User;
import com.mediLinkAI.entity.enums.UserStatus;
import com.mediLinkAI.exception.MediLinkAI;
import com.mediLinkAI.repository.User.OTPRepository;
import com.mediLinkAI.repository.User.UserRepository;
import com.mediLinkAI.utility.Data;
import com.mediLinkAI.utility.Utilities;

@Service(value = "userService")
public class UserServiceImp1 implements UserService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JavaMailSender mailSender;

    @Autowired
    private OTPRepository otpRepository;

    @Override
    public UserDTO registerUser(UserDTO userDTO) throws MediLinkAI {
        // Check if email already exists
        Optional<User> optional = userRepository.findByEmail(userDTO.getEmail());
        if (optional.isPresent()) {
            throw new MediLinkAI("USER_FOUND");
        }

        // Hash the phone number (SHA-256 for deterministic lookup)
        String phoneHash = Utilities.hashPhone(userDTO.getPhone());

        // Check if phone already registered using hashed value
        if (userRepository.existsByPhoneHash(phoneHash)) {
            throw new MediLinkAI("PHONE_ALREADY_REGISTERED");
        }

        // Build User entity
        User user = new User();
        // UUID is auto-generated by @GeneratedValue(strategy = GenerationType.UUID)
        user.setEmail(userDTO.getEmail());
        user.setPhoneHash(phoneHash); // Store SHA-256 hashed phone
        user.setPasswordHash(passwordEncoder.encode(userDTO.getPassword())); // BCrypt encoded password
        user.setStatus(UserStatus.ACTIVE); // Default status is ACTIVE

        // Conditional MFA setup
        if (userDTO.isMfaRequired()) {
            user.setMfaEnabled(true);
            user.setMfaSecret(Utilities.generateMfaSecret()); // Generate TOTP-compatible secret
        } else {
            user.setMfaEnabled(false);
            // mfaSecret remains null — not inserted in DB
        }

        user = userRepository.save(user);
        return user.toDTO();
    }

    @Override
    public UserDTO loginUser(LoginDTO loginDTO) throws MediLinkAI {
        String identifier = loginDTO.getIdentifier();
        User user;
        if (identifier.contains("@")) {
            user = userRepository.findByEmail(identifier).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        } else {
            user = userRepository.findByPhoneHash(Utilities.hashPhone(identifier)).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        }

        if (!passwordEncoder.matches(loginDTO.getPassword(), user.getPasswordHash()))
            throw new MediLinkAI("INVALID_PASSWORD");

        UserDTO responseDTO = user.toDTO();

        if (user.getMfaEnabled() != null && user.getMfaEnabled()) {
            try {
                this.sendOtp(user.getEmail());
            } catch (Exception e) {
                throw new MediLinkAI("MFA_OTP_SEND_FAILED");
            }
            responseDTO.setMfaRequired(true);
        } else {
            responseDTO.setMfaRequired(false);
        }

        return responseDTO;
    }

    @Override
    public void sendOtp(String identifier) throws Exception {
        User user;
        if (identifier.contains("@")) {
            user = userRepository.findByEmail(identifier).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        } else {
            user = userRepository.findByPhoneHash(Utilities.hashPhone(identifier)).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        }
        String targetEmail = user.getEmail();

        MimeMessage mm = mailSender.createMimeMessage();
        MimeMessageHelper message = new MimeMessageHelper(mm, true);
        message.setTo(targetEmail);
        message.setSubject("OTP Verification - NutriTrack");
        String otp = Utilities.generateOtp();

        // Check if OTP record exists for this email
        Optional<OTP> existingOtp = otpRepository.findByEmail(targetEmail);
        OTP otpSave;

        if (existingOtp.isPresent()) {
            // Update existing OTP record
            otpSave = existingOtp.get();
            otpSave.setOtp(otp);
            otpSave.setCreatedAt(LocalDateTime.now());
        } else {
            // Create new OTP record
            otpSave = new OTP(null, targetEmail, otp, LocalDateTime.now());
        }

        otpRepository.save(otpSave);
        message.setText(Data.getOtpEmailHtml(otp, user.getEmail()), true);
        mailSender.send(mm);
    }

    @Override
    public Boolean verifyOtp(String identifier, String otp) throws MediLinkAI {
        // Verify user exists
        User user;
        if (identifier.contains("@")) {
            user = userRepository.findByEmail(identifier).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        } else {
            user = userRepository.findByPhoneHash(Utilities.hashPhone(identifier)).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        }
        String targetEmail = user.getEmail();

        // Find OTP record
        Optional<OTP> otpRecord = otpRepository.findByEmailAndOtp(targetEmail, otp);
        if (otpRecord.isEmpty()) {
            throw new MediLinkAI("INVALID_OTP");
        }

        OTP otpEntity = otpRecord.get();

        // Check if OTP is expired (10 minutes)
        LocalDateTime expiryTime = otpEntity.getCreatedAt().plusMinutes(10);
        if (LocalDateTime.now().isAfter(expiryTime)) {
            otpRepository.delete(otpEntity);
            throw new MediLinkAI("OTP_EXPIRED");
        }

        // Delete OTP after successful verification (one-time use)
        otpRepository.delete(otpEntity);

        return true;
    }

    @Override
    public ResponseDTO changePassword(LoginDTO loginDTO) throws MediLinkAI {
        String identifier = loginDTO.getIdentifier();
        User user;
        if (identifier.contains("@")) {
            user = userRepository.findByEmail(identifier).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        } else {
            user = userRepository.findByPhoneHash(Utilities.hashPhone(identifier)).orElseThrow(() -> new MediLinkAI("USER_NOT_FOUND"));
        }
        user.setPasswordHash(passwordEncoder.encode(loginDTO.getPassword()));
        userRepository.save(user);
        return new ResponseDTO("Password changed successfully");
    }

    @Scheduled(fixedRate = 10000)
    public void removeExpiredOTP() {
        List<OTP> expiredOTPs = otpRepository.findAllByCreatedAtBefore(LocalDateTime.now().minusMinutes(10));
        if (expiredOTPs.size() > 0)
            otpRepository.deleteAll(expiredOTPs);
        System.out.println("Expired OTPs removed: " + expiredOTPs.size());
    }
}
